name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest

    steps:
    # this step will automatically clone the code of the current branch into the runner
    - name: Clone the Repo
      uses: actions/checkout@v4

       # this step will install the linting tool 
    - name: install the linter
      run: pip install ruff
